name: Run Test

on:
  pull_request:
    branches:
      - main
      - 'develop'
  workflow_dispatch:

jobs:
  api-test:
    if: contains(github.event.pull_request.labels.*.name, 'api')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        working-directory: ./api
        run: |
          echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Install dependencies
        working-directory: ./api
        run: |
          npm ci
      - name: Run API unit tests
        working-directory: ./api
        run: |
          npm run test:cov
